added scalastyle check commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -46,5 +46,13 @@ then
 	exit 1
 fi
 
+java -jar .git/scalastyle/scalastyle-batch_2.9.1.jar --config .git/scalastyle/lib/scalastyle_config.xml -q true -w true src/main/scala
+
+if [ $? != 0 ]
+then
+    echo "Failed the scalastyle check."
+    exit 1
+fi
+
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
